CREATE DATABASE IF NOT EXISTS stalker CHARACTER SET 'UTF8';

USE stalker;

CREATE TABLE IF NOT EXISTS message (
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
m_topic VARCHAR(255) NOT NULL,
m_tag   VARCHAR(255) NOT NULL,
msg_id  VARCHAR(255),
tracer_id VARCHAR(255) NOT NULL,
born_host VARCHAR(255) NOT NULL,
status  VARCHAR(255),
source  VARCHAR(255),
producer_group VARCHAR(255),
broker  VARCHAR(255),
message_queue INT,
offset VARCHAR(255),
create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
time_stamp BIGINT NOT NULL DEFAULT 0
) ENGINE = INNODB;

